-- Keep-alive table migration
-- Run this SQL in your Supabase SQL Editor to add the keep-alive functionality
-- This prevents your Supabase project from pausing due to inactivity

-- Keep-alive table to prevent Supabase project from pausing due to inactivity
-- This table is used by the /api/keep-alive endpoint which runs on a cron schedule
CREATE TABLE IF NOT EXISTS public.keep_alive (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NULL DEFAULT '',
    random UUID NULL DEFAULT gen_random_uuid(),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Insert some placeholder data for the keep-alive queries
INSERT INTO public.keep_alive(name) VALUES
    ('placeholder'),
    ('example'),
    ('keep-alive')
ON CONFLICT DO NOTHING;

-- Enable RLS for keep_alive table
ALTER TABLE public.keep_alive ENABLE ROW LEVEL SECURITY;

-- Create policy for keep_alive table (read-only for keep-alive functionality)
DROP POLICY IF EXISTS "Enable read access for all users" ON public.keep_alive;
CREATE POLICY "Enable read access for all users" ON public.keep_alive FOR SELECT USING (true);

